name: create aks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - run: |
            az aks create --resource-group ${{ secrets.RG_NAME }} --name ${{ secrets.AKS_NAME }} --node-count 1 --generate-ssh-keys
            
